name: zopo
description: This project is just a small app created by Bruno$0 to pratice the Dart/Flutter Language.  

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true #"launcher_icon"
  ios: true
  image_path: "assets/launcher/form.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  #remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/launcher/form.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path:   "assets/launcher/form.png"
    icon_size: 256 # min:48, max:256, default: 48

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
